// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package signer

import (
	"connectrpc.com/connect"
	"context"
	"github.com/davidmdm/connect-playground/internal/proto/signer/v1"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			SignFunc: func(contextMoqParam context.Context, request *connect.Request[signerv1.SignRequest]) (*connect.Response[signerv1.SignResponse], error) {
//				panic("mock out the Sign method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// SignFunc mocks the Sign method.
	SignFunc func(contextMoqParam context.Context, request *connect.Request[signerv1.SignRequest]) (*connect.Response[signerv1.SignResponse], error)

	// calls tracks calls to the methods.
	calls struct {
		// Sign holds details about calls to the Sign method.
		Sign []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Request is the request argument value.
			Request *connect.Request[signerv1.SignRequest]
		}
	}
	lockSign sync.RWMutex
}

// Sign calls SignFunc.
func (mock *ClientMock) Sign(contextMoqParam context.Context, request *connect.Request[signerv1.SignRequest]) (*connect.Response[signerv1.SignResponse], error) {
	if mock.SignFunc == nil {
		panic("ClientMock.SignFunc: method is nil but Client.Sign was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Request         *connect.Request[signerv1.SignRequest]
	}{
		ContextMoqParam: contextMoqParam,
		Request:         request,
	}
	mock.lockSign.Lock()
	mock.calls.Sign = append(mock.calls.Sign, callInfo)
	mock.lockSign.Unlock()
	return mock.SignFunc(contextMoqParam, request)
}

// SignCalls gets all the calls that were made to Sign.
// Check the length with:
//
//	len(mockedClient.SignCalls())
func (mock *ClientMock) SignCalls() []struct {
	ContextMoqParam context.Context
	Request         *connect.Request[signerv1.SignRequest]
} {
	var calls []struct {
		ContextMoqParam context.Context
		Request         *connect.Request[signerv1.SignRequest]
	}
	mock.lockSign.RLock()
	calls = mock.calls.Sign
	mock.lockSign.RUnlock()
	return calls
}
