// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/signer/v1/signer.proto

package signerv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/davidmdm/connect-playground/internal/proto/signer/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// SignerServiceName is the fully-qualified name of the SignerService service.
	SignerServiceName = "proto.signer.v1.SignerService"
)

// SignerServiceClient is a client for the proto.signer.v1.SignerService service.
type SignerServiceClient interface {
	Sign(context.Context, *connect_go.Request[v1.SignRequest]) (*connect_go.Response[v1.SignResponse], error)
}

// NewSignerServiceClient constructs a client for the proto.signer.v1.SignerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSignerServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) SignerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &signerServiceClient{
		sign: connect_go.NewClient[v1.SignRequest, v1.SignResponse](
			httpClient,
			baseURL+"/proto.signer.v1.SignerService/Sign",
			opts...,
		),
	}
}

// signerServiceClient implements SignerServiceClient.
type signerServiceClient struct {
	sign *connect_go.Client[v1.SignRequest, v1.SignResponse]
}

// Sign calls proto.signer.v1.SignerService.Sign.
func (c *signerServiceClient) Sign(ctx context.Context, req *connect_go.Request[v1.SignRequest]) (*connect_go.Response[v1.SignResponse], error) {
	return c.sign.CallUnary(ctx, req)
}

// SignerServiceHandler is an implementation of the proto.signer.v1.SignerService service.
type SignerServiceHandler interface {
	Sign(context.Context, *connect_go.Request[v1.SignRequest]) (*connect_go.Response[v1.SignResponse], error)
}

// NewSignerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSignerServiceHandler(svc SignerServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/proto.signer.v1.SignerService/Sign", connect_go.NewUnaryHandler(
		"/proto.signer.v1.SignerService/Sign",
		svc.Sign,
		opts...,
	))
	return "/proto.signer.v1.SignerService/", mux
}

// UnimplementedSignerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSignerServiceHandler struct{}

func (UnimplementedSignerServiceHandler) Sign(context.Context, *connect_go.Request[v1.SignRequest]) (*connect_go.Response[v1.SignResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.signer.v1.SignerService.Sign is not implemented"))
}
