// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/signer/v1/signer.proto

package signerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/davidmdm/connect-playground/internal/proto/signer/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SignerServiceName is the fully-qualified name of the SignerService service.
	SignerServiceName = "proto.signer.v1.SignerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SignerServiceSignProcedure is the fully-qualified name of the SignerService's Sign RPC.
	SignerServiceSignProcedure = "/proto.signer.v1.SignerService/Sign"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	signerServiceServiceDescriptor    = v1.File_proto_signer_v1_signer_proto.Services().ByName("SignerService")
	signerServiceSignMethodDescriptor = signerServiceServiceDescriptor.Methods().ByName("Sign")
)

// SignerServiceClient is a client for the proto.signer.v1.SignerService service.
type SignerServiceClient interface {
	Sign(context.Context, *connect.Request[v1.SignRequest]) (*connect.Response[v1.SignResponse], error)
}

// NewSignerServiceClient constructs a client for the proto.signer.v1.SignerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSignerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SignerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &signerServiceClient{
		sign: connect.NewClient[v1.SignRequest, v1.SignResponse](
			httpClient,
			baseURL+SignerServiceSignProcedure,
			connect.WithSchema(signerServiceSignMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// signerServiceClient implements SignerServiceClient.
type signerServiceClient struct {
	sign *connect.Client[v1.SignRequest, v1.SignResponse]
}

// Sign calls proto.signer.v1.SignerService.Sign.
func (c *signerServiceClient) Sign(ctx context.Context, req *connect.Request[v1.SignRequest]) (*connect.Response[v1.SignResponse], error) {
	return c.sign.CallUnary(ctx, req)
}

// SignerServiceHandler is an implementation of the proto.signer.v1.SignerService service.
type SignerServiceHandler interface {
	Sign(context.Context, *connect.Request[v1.SignRequest]) (*connect.Response[v1.SignResponse], error)
}

// NewSignerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSignerServiceHandler(svc SignerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	signerServiceSignHandler := connect.NewUnaryHandler(
		SignerServiceSignProcedure,
		svc.Sign,
		connect.WithSchema(signerServiceSignMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.signer.v1.SignerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SignerServiceSignProcedure:
			signerServiceSignHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSignerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSignerServiceHandler struct{}

func (UnimplementedSignerServiceHandler) Sign(context.Context, *connect.Request[v1.SignRequest]) (*connect.Response[v1.SignResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.signer.v1.SignerService.Sign is not implemented"))
}
