package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/bufbuild/connect-go"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	greetv1 "github.com/davidmdm/connect-playground/internal/proto/greet/v1"        // generated by protoc-gen-go
	"github.com/davidmdm/connect-playground/internal/proto/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
)

type GreetServer struct{}

func (s *GreetServer) Greet(ctx context.Context, req *connect.Request[greetv1.GreetRequest]) (*connect.Response[greetv1.GreetResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	})
	res.Header().Set("Greet-Version", "v1")

	return res, nil
}

func main() {
	greeter := &GreetServer{}

	mux := http.NewServeMux()

	path, handler := greetv1connect.NewGreetServiceHandler(greeter)
	mux.Handle(path, WrapperMiddleware(handler))

	// Use h2c so we can serve HTTP/2 without TLS.
	http.ListenAndServe(":8080", h2c.NewHandler(mux, &http2.Server{}))
}

type RWWrapper struct {
	http.ResponseWriter
}

func WrapperMiddleware(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.ServeHTTP(RWWrapper{w}, r)
	})
}
