package main

import (
	"context"
	"fmt"
	"net/http"

	"github.com/bufbuild/connect-go"
	"github.com/circleci/backplane-go/environment"
	"github.com/circleci/samwise/observability"
	"github.com/gin-gonic/gin"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	greetv1 "github.com/davidmdm/connect-playground/internal/proto/greet/v1"        // generated by protoc-gen-go
	"github.com/davidmdm/connect-playground/internal/proto/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
)

type GreetServer struct{}

func (s *GreetServer) Greet(ctx context.Context, req *connect.Request[greetv1.GreetRequest]) (*connect.Response[greetv1.GreetResponse], error) {
	res := connect.NewResponse(&greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	})
	res.Header().Set("Greet-Version", "v1")

	return res, nil
}

func main() {
	ctx, teardown := observability.MustReportingContext(context.Background(), environment.FromOS())
	defer teardown(ctx)

	greeter := &GreetServer{}

	gin.SetMode(gin.ReleaseMode)
	engine := gin.New()

	engine.Use(observability.Middlewares(observability.FromContext(ctx))...)

	engine.Any(GinAdaptor(greetv1connect.NewGreetServiceHandler(greeter)))

	http.ListenAndServe(":8080", h2c.NewHandler(engine, &http2.Server{}))
}

func GinAdaptor(path string, h http.Handler) (string, gin.HandlerFunc) {
	return path + "*rest", func(c *gin.Context) { h.ServeHTTP(c.Writer, c.Request) }
}
